# SPDX-FileCopyrightText: 2025 SGC contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Mirotalk installation tasks
  when: mirotalk_enabled | bool
  tags:
    - setup-all
    - setup-mirotalk
    - install-all
    - install-mirotalk
  block:
    - name: Validate Mirotalk configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Mirotalk
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Mirotalk uninstallation tasks
  when: not mirotalk_enabled | bool
  tags:
    - setup-all
    - setup-mirotalk
  block:
    - name: Uninstall Mirotalk
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
